# Generated by Django 4.1.7 on 2023-09-25 03:15

from django.db import migrations, models
import spotlight.models
import spotlight.storage_backends


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spotlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(default=None, max_length=20)),
                ('first_name_husband', models.CharField(default=None, max_length=20)),
                ('first_name_wife', models.CharField(default=None, max_length=20)),
                ('asked', models.BooleanField(default=False)),
                ('date_asked', models.DateField(default=None)),
                ('ready', models.DateField(default=False)),
                ('date_ready', models.DateField(default=None)),
                ('planned', models.BooleanField(default=False)),
                ('date_planned', models.DateField(default=None)),
                ('published', models.BooleanField(default=False)),
                ('date_published', models.DateField(default=None)),
                ('date_joined', models.DateField(default=None)),
                ('member_type', models.CharField(choices=[('O', 'old'), ('N', 'new'), ('W', 'ward_council')], default='O', max_length=1)),
                ('bio', models.TextField(default=None)),
                ('image', models.ImageField(default=None, storage=spotlight.storage_backends.PrivateMediaStorage(), upload_to=spotlight.models.Spotlight.spotlight_image_upload_path)),
            ],
        ),
    ]
