# Generated by Django 4.1.7 on 2023-09-25 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotlight', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotlight',
            name='member_type',
            field=models.CharField(choices=[('O', 'Old'), ('N', 'New'), ('W', 'Ward Council')], default='O', max_length=1),
        ),
        migrations.AlterField(
            model_name='spotlight',
            name='ready',
            field=models.BooleanField(default=False),
        ),
    ]
