# Generated by Django 4.1.7 on 2023-09-25 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotlight', '0002_alter_spotlight_member_type_alter_spotlight_ready'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spotlight',
            name='asked',
        ),
        migrations.RemoveField(
            model_name='spotlight',
            name='planned',
        ),
        migrations.RemoveField(
            model_name='spotlight',
            name='published',
        ),
        migrations.RemoveField(
            model_name='spotlight',
            name='ready',
        ),
        migrations.AddField(
            model_name='spotlight',
            name='status',
            field=models.CharField(choices=[('Asked', 'Asked'), ('Ready', 'Ready'), ('Planned', 'Planned'), ('Published', 'Published')], default=None, max_length=10, null=True),
        ),
    ]
