# Generated by Django 4.1.7 on 2023-09-25 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotlight', '0003_remove_spotlight_asked_remove_spotlight_planned_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotlight',
            name='status',
            field=models.CharField(choices=[('NS', 'Not Started'), ('A', 'Asked'), ('R', 'Ready'), ('P', 'Planned'), ('S', 'Slacked')], default='NS', max_length=2),
        ),
    ]
