# Generated by Django 4.1.7 on 2023-09-25 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotlight', '0004_alter_spotlight_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spotlight',
            old_name='date_published',
            new_name='date_slacked',
        ),
    ]
