# Generated by Django 4.1.7 on 2023-09-25 18:01

from django.db import migrations, models
import spotlight.models
import spotlight.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('spotlight', '0005_rename_date_published_spotlight_date_slacked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotlight',
            name='bio',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='spotlight',
            name='date_asked',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='spotlight',
            name='date_joined',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='spotlight',
            name='date_planned',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='spotlight',
            name='date_ready',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='spotlight',
            name='date_slacked',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='spotlight',
            name='first_name_husband',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='spotlight',
            name='first_name_wife',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='spotlight',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, storage=spotlight.storage_backends.PrivateMediaStorage(), upload_to=spotlight.models.Spotlight.spotlight_image_upload_path),
        ),
        migrations.AlterField(
            model_name='spotlight',
            name='last_name',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='spotlight',
            name='member_type',
            field=models.CharField(blank=True, choices=[('O', 'Old'), ('N', 'New'), ('W', 'Ward Council')], default='O', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='spotlight',
            name='status',
            field=models.CharField(blank=True, choices=[('NS', 'Not Started'), ('A', 'Asked'), ('R', 'Ready'), ('P', 'Planned'), ('S', 'Slacked')], default='NS', max_length=2, null=True),
        ),
    ]
